### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by ptheunis** [cwstra/rpdiscordbot#2]
I got it running my commenting out the "random"  stuff but it doesn't look like it's up to date with the latest bot running in the PTU server.

Could i get the latest version? the page numbers are very useful :)

**Comment by cwstra** [comment]
It is not, but instead it has a successor:
https://github.com/cwstra/rpdiscordrewrite
I've yet to make the rewrite easily installible, but you can use the `invite` command to invite the bot in the PTU Server wherever you like.
